---
blank_issues_enabled: false
contact_links:
  - name: Kakarot RPC Community Support
    url: https://github.com/sayajin-labs/kakarot-rpc/discussions
    about: Please ask and answer questions here.
